import api from '@/lib/axios';

const BASE = '/billing';

export const billingApi = {
  plans: () => api.get(`${BASE}/plans`),
  stripeStatus: () => api.get(`${BASE}/stripe/status`),
  overview: () => api.get(`${BASE}/overview`),
  usage: () => api.get(`${BASE}/usage`),
  checkout: (data) => api.post(`${BASE}/checkout`, data),
  confirmCheckout: (sessionId) => api.post(`${BASE}/checkout/confirm`, { sessionId }),
  portal: () => api.post(`${BASE}/portal`),
  cancel: (data) => api.post(`${BASE}/cancel`, data),
  payments: (params) => api.get(`${BASE}/payments`, { params }),
  invoices: (params) => api.get(`${BASE}/invoices`, { params }),
  validateCoupon: (data) => api.post(`${BASE}/coupons/validate`, data),
  redeemCoupon: (code) => api.post(`${BASE}/coupons/redeem`, { code }),
  referrals: () => api.get(`${BASE}/referrals`),
  applyReferral: (code) => api.post(`${BASE}/referrals/apply`, { code }),
  organizations: () => api.get(`${BASE}/organizations`),
  createOrganization: (data) => api.post(`${BASE}/organizations`, data),
  inviteMember: (orgId, data) => api.post(`${BASE}/organizations/${orgId}/invite`, data),
  listMembers: (orgId) => api.get(`${BASE}/organizations/${orgId}/members`),
  getPreferences: () => api.get(`${BASE}/settings/preferences`),
  updatePreferences: (data) => api.patch(`${BASE}/settings/preferences`, data),
  security: () => api.get(`${BASE}/settings/security`),
  setup2fa: () => api.post(`${BASE}/settings/security/2fa/setup`),
  enable2fa: (token) => api.post(`${BASE}/settings/security/2fa/enable`, { token }),
  disable2fa: () => api.post(`${BASE}/settings/security/2fa/disable`),
  revokeSession: (sessionId) => api.delete(`${BASE}/settings/security/sessions/${sessionId}`),
  trustDevice: (data) => api.post(`${BASE}/settings/security/trust-device`, data),
  getBillingAddress: () => api.get(`${BASE}/settings/billing-address`),
  updateBillingAddress: (data) => api.put(`${BASE}/settings/billing-address`, data),
  exportData: () => api.post(`${BASE}/settings/export-data`),
  deleteAccount: (password) => api.post(`${BASE}/settings/delete-account`, { password }),
  developerDashboard: () => api.get(`${BASE}/developer`),
  listApiKeys: () => api.get(`${BASE}/developer/keys`),
  createApiKey: (data) => api.post(`${BASE}/developer/keys`, data),
  revokeApiKey: (id) => api.delete(`${BASE}/developer/keys/${id}`),
  listWebhooks: () => api.get(`${BASE}/developer/webhooks`),
  createWebhook: (data) => api.post(`${BASE}/developer/webhooks`, data),
  deleteWebhook: (id) => api.delete(`${BASE}/developer/webhooks/${id}`),
  webhookLogs: (id, params) => api.get(`${BASE}/developer/webhooks/${id}/logs`, { params }),
};

export const adminSaasApi = {
  revenue: (params) => api.get('/admin/saas/revenue', { params }),
  plans: () => api.get('/admin/saas/plans'),
  updatePlan: (id, data) => api.patch(`/admin/saas/plans/${id}`, data),
  coupons: (params) => api.get('/admin/saas/coupons', { params }),
  createCoupon: (data) => api.post('/admin/saas/coupons', data),
  subscriptions: (params) => api.get('/admin/saas/subscriptions', { params }),
  payments: (params) => api.get('/admin/saas/payments', { params }),
  refund: (id, data) => api.post(`/admin/saas/payments/${id}/refund`, data),
  referrals: (params) => api.get('/admin/saas/referrals', { params }),
};
